package isi.died.tp.controller;

public enum OpcionesMenu {
	GESTION_ENTIDADES, GESTION_LOGISTICA, GESTION_ENVIOS,
	AGREGAR_INSUMO, MODIFICAR_INSUMO, ELIMINAR_INSUMO,
	AGREGAR_PLANTA, MODIFICAR_PLANTA, ELIMINAR_PLANTA,
	AGREGAR_CAMION, MODIFICAR_CAMION, ELIMINAR_CAMION,
	AGREGAR_STOCK, MODIFICAR_STOCK, ELIMINAR_STOCK,
	AGREGAR_RUTA, MODIFICAR_RUTA, ELIMINAR_RUTA, BUSCAR_INSUMOS;
}
