package isi.died.tp.controller;

public enum OpcionesMenu {
	AGREGAR_INSUMO, MODIFICAR_INSUMO, ELIMINAR_INSUMO,
	AGREGAR_PLANTA, MODIFICAR_PLANTA, ELIMINAR_PLANTA,
	AGREGAR_CAMION, MODIFICAR_CAMION, ELIMINAR_CAMION,
	AGREGAR_STOCK;
}
